logging:
  logs:
    default:
      level: INFO
storage:
  module: file_system
  root: /data
apps:
  tls:
    certificates:
      automate:
        - rtc.beachvolleyballmedia.com
        - turn.beachvolleyballmedia.com
  layer4:
    servers:
      main:
        listen: [":443"]
        routes:
          - match:
              - tls:
                  sni:
                    - turn.beachvolleyballmedia.com
            handle:
              - handler: tls
              - handler: proxy
                upstreams:
                  - dial: ["__PUBLIC_IP__:5349"]
          - match:
              - tls:
                  sni:
                    - rtc.beachvolleyballmedia.com
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["localhost:7880"]
